[package]
name = "talos"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "MIT"

[dependencies]
chacha20 = { version = "0.10.0", default-features = false, features = [
    "rng",
    "zeroize",
] }
smoltcp = { version = "0.13.1", default-features = false, features = [
    "medium-ethernet",
    "proto-ipv4",
    "socket-tcp",
] }
ssh-key = { version = "0.7.0-rc.10", default-features = false, features = [
    "alloc",
    "ed25519",
] }
signature = { version = "3.0.0", default-features = false }
zeroize = { version = "=1.8.1", default-features = false }

[[bin]]
name = "talos"
test = true
bench = false
