[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "targets/aarch64-talos-virt.json"

[target.aarch64-talos-virt]
runner = "./scripts/qemu-runner.sh"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-Map=target/talos-aarch64-virt.map",
]

[target.aarch64-talos-rpi5-bcm2712]
rustflags = [
    "-C", "link-arg=-Tlinker-rpi5.ld",
    "-C", "link-arg=-Map=target/talos-rpi5-bcm2712.map",
]
