#!/bin/sh
set -eu

env \
    -u TALOS_RPI5_EXCEPTION_REPORT_DIAGNOSTIC \
    -u TALOS_RPI5_NORMAL_EXCEPTION_REPORT_DIAGNOSTIC \
    -u TALOS_RPI5_EXCEPTION_RETURN_DIAGNOSTIC \
    -u TALOS_RPI5_FULL_PANIC_INFO_DIAGNOSTIC \
    TALOS_RPI5_PANIC_REPORT_DIAGNOSTIC=1 \
    TALOS_RPI5_NESTED_PANIC_DIAGNOSTIC=1 \
    ./scripts/rpi5-image.sh
