#!/bin/sh
set -eu

env \
    -u TALOS_RPI5_CARGO_ASM_UART_PROOF \
    -u TALOS_RPI5_TRANSITION_DIAGNOSTIC \
    -u TALOS_RPI5_RUST_ENTRY_DIAGNOSTIC \
    -u TALOS_RPI5_MINIMAL_FORMAT_DIAGNOSTIC \
    -u TALOS_RPI5_EXCEPTION_REPORT_DIAGNOSTIC \
    -u TALOS_RPI5_DYNAMIC_FORMAT_FALLBACK_DIAGNOSTIC \
    -u TALOS_RPI5_FMT_SINK_DIAGNOSTIC \
    -u TALOS_RPI5_FMT_STATIC_SINK_DIAGNOSTIC \
    -u TALOS_RPI5_FMT_SINK_DIRECT_DIAGNOSTIC \
    -u TALOS_RPI5_FMT_SINK_DYN_DIRECT_DIAGNOSTIC \
    -u TALOS_RPI5_FMT_SINK_FNPTR_DIRECT_DIAGNOSTIC \
    -u TALOS_RPI5_FNPTR_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_TEXT_SECTION_DIAGNOSTIC \
    -u TALOS_RPI5_VECTOR_SECTION_DIAGNOSTIC \
    -u TALOS_RPI5_TEXT_BOOT_FAR_DIAGNOSTIC \
    -u TALOS_RPI5_TEXT_BOOT_NEAR_DIAGNOSTIC \
    -u TALOS_RPI5_TEXT_BOOT_NEAR_BRANCH_DIAGNOSTIC \
    -u TALOS_RPI5_TEXT_BOOT_NEXT_BRANCH_DIAGNOSTIC \
    -u TALOS_RPI5_FALLTHROUGH_RUST_DIAGNOSTIC \
    -u TALOS_RPI5_POST_STACK_NOP_DIAGNOSTIC \
    -u TALOS_RPI5_POST_STACK_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_INDIRECT_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_DIRECT_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_TO_RUST_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_INDIRECT_TO_RUST_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_BTI_INDIRECT_TO_RUST_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_TEXT_INDIRECT_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_TEXT_DIRECT_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_ASM_TEXT_JC_INDIRECT_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_BTI_EXCEPTION_CLASSIFIER_DIAGNOSTIC \
    -u TALOS_RPI5_BTI_CLASSIFIER_WITH_BRK_PRECHECK_DIAGNOSTIC \
    -u TALOS_RPI5_DIRECT_EXCEPTION_CONTROL_DIAGNOSTIC \
    -u TALOS_RPI5_DIRECT_EXCEPTION_IMMEDIATE_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_BRK_ERET_RESUME_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_BRK_ELR_WRITE_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_BRK_SPSR_ERET_RESET_DIAGNOSTIC \
    -u TALOS_RPI5_BRK_ERET_UART_MARKER_DIAGNOSTIC \
    -u TALOS_RPI5_READABLE_BOOT_LOG_DIAGNOSTIC \
    TALOS_RPI5_BRK_SPSR_HANDLER_RESET_DIAGNOSTIC=1 \
    ./scripts/rpi5-image.sh
