//! Operator-seeded CSPRNG readiness boundary.
//!
//! This module is the only Talos-owned consumer of raw operator seed bytes in
//! the current Phase 12.5 slice. It does not print, digest, fingerprint, retain,
//! or expose seed material or generated bytes through diagnostics or evidence.

use chacha20::{
    ChaCha20Rng,
    rand_core::{Rng, SeedableRng},
};
use zeroize::Zeroize;

use crate::{
    entropy::{
        OPERATOR_SEED_MAX_DIAGNOSTIC_BYTES, OPERATOR_SEED_MIN_SUFFICIENT_BYTES, OPERATOR_SEED_PATH,
    },
    initramfs::ReadOnlyInitramfs,
    posix::PosixError,
};

pub(crate) const CSPRNG_SEED_BYTES: usize = 32;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CsprngReadinessState {
    MissingSeed,
    InvalidSeed,
    InsufficientSeed,
    ConditioningFailed,
    Ready,
}

impl CsprngReadinessState {
    pub(crate) const fn is_ready(self) -> bool {
        matches!(self, Self::Ready)
    }

    pub(crate) const fn name(self) -> &'static str {
        match self {
            Self::MissingSeed => "csprng-missing-seed",
            Self::InvalidSeed => "csprng-invalid-seed",
            Self::InsufficientSeed => "csprng-insufficient-seed",
            Self::ConditioningFailed => "csprng-conditioning-failed",
            Self::Ready => "csprng-ready",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct CsprngReadinessReport {
    state: CsprngReadinessState,
    seed_len: Option<usize>,
}

impl CsprngReadinessReport {
    pub(crate) const fn missing_seed() -> Self {
        Self {
            state: CsprngReadinessState::MissingSeed,
            seed_len: None,
        }
    }

    pub(crate) const fn invalid_seed(seed_len: Option<usize>) -> Self {
        Self {
            state: CsprngReadinessState::InvalidSeed,
            seed_len,
        }
    }

    pub(crate) const fn insufficient_seed(seed_len: usize) -> Self {
        Self {
            state: CsprngReadinessState::InsufficientSeed,
            seed_len: Some(seed_len),
        }
    }

    const fn conditioning_failed(seed_len: usize) -> Self {
        Self {
            state: CsprngReadinessState::ConditioningFailed,
            seed_len: Some(seed_len),
        }
    }

    const fn ready(seed_len: usize) -> Self {
        Self {
            state: CsprngReadinessState::Ready,
            seed_len: Some(seed_len),
        }
    }

    pub(crate) const fn state(self) -> CsprngReadinessState {
        self.state
    }

    pub(crate) const fn seed_len(self) -> Option<usize> {
        self.seed_len
    }

    pub(crate) const fn cryptographic_strength(self) -> bool {
        self.state.is_ready()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CsprngError {
    NotReady(CsprngReadinessState),
}

pub(crate) struct OperatorSeededCsprng {
    rng: Option<ChaCha20Rng>,
    readiness: CsprngReadinessReport,
}

impl OperatorSeededCsprng {
    pub(crate) fn from_initramfs(initramfs: ReadOnlyInitramfs) -> Self {
        match initramfs.regular_file_bytes(OPERATOR_SEED_PATH) {
            Ok(seed_material) => Self::from_seed_bytes(seed_material),
            Err(PosixError::NoEntry) => Self::not_ready(CsprngReadinessReport::missing_seed()),
            Err(PosixError::IsDirectory) => {
                Self::not_ready(CsprngReadinessReport::invalid_seed(None))
            }
            Err(_) => Self::not_ready(CsprngReadinessReport::invalid_seed(None)),
        }
    }

    pub(crate) fn from_seed_bytes(seed_material: &[u8]) -> Self {
        let seed_len = seed_material.len();
        if seed_len == 0 || seed_len > OPERATOR_SEED_MAX_DIAGNOSTIC_BYTES {
            return Self::not_ready(CsprngReadinessReport::invalid_seed(Some(seed_len)));
        }
        if seed_len < OPERATOR_SEED_MIN_SUFFICIENT_BYTES {
            return Self::not_ready(CsprngReadinessReport::insufficient_seed(seed_len));
        }

        let Some(mut conditioned_seed) = condition_operator_seed(seed_material) else {
            return Self::not_ready(CsprngReadinessReport::conditioning_failed(seed_len));
        };
        let rng = ChaCha20Rng::from_seed(conditioned_seed);
        conditioned_seed.zeroize();

        Self {
            rng: Some(rng),
            readiness: CsprngReadinessReport::ready(seed_len),
        }
    }

    const fn not_ready(readiness: CsprngReadinessReport) -> Self {
        Self {
            rng: None,
            readiness,
        }
    }

    pub(crate) const fn readiness(&self) -> CsprngReadinessReport {
        self.readiness
    }

    pub(crate) fn fill_bytes(&mut self, output: &mut [u8]) -> Result<(), CsprngError> {
        let Some(rng) = self.rng.as_mut() else {
            output.zeroize();
            return Err(CsprngError::NotReady(self.readiness.state()));
        };

        rng.fill_bytes(output);
        Ok(())
    }
}

fn condition_operator_seed(seed_material: &[u8]) -> Option<[u8; CSPRNG_SEED_BYTES]> {
    if seed_material.len() < OPERATOR_SEED_MIN_SUFFICIENT_BYTES
        || seed_material.len() > OPERATOR_SEED_MAX_DIAGNOSTIC_BYTES
    {
        return None;
    }

    let mut conditioned = [0u8; CSPRNG_SEED_BYTES];
    conditioned.copy_from_slice(&seed_material[..CSPRNG_SEED_BYTES]);

    for (index, byte) in seed_material[CSPRNG_SEED_BYTES..]
        .iter()
        .copied()
        .enumerate()
    {
        let slot = index % CSPRNG_SEED_BYTES;
        let mirror = (CSPRNG_SEED_BYTES - 1) - slot;
        let rotated = byte.rotate_left((index & 7) as u32);
        conditioned[slot] ^= rotated;
        conditioned[mirror] = conditioned[mirror].wrapping_add(byte ^ (index as u8));
    }

    for (index, byte) in seed_material
        .len()
        .to_le_bytes()
        .iter()
        .copied()
        .enumerate()
    {
        let slot = index % CSPRNG_SEED_BYTES;
        conditioned[slot] ^= byte.rotate_left((index & 7) as u32);
    }

    Some(conditioned)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::initramfs::{DirectoryEntry, InitramfsNode, ReadOnlyInitramfs};

    #[test_case]
    fn missing_invalid_and_insufficient_operator_seeds_fail_closed() {
        let missing = OperatorSeededCsprng::from_initramfs(missing_seed_initramfs());
        let directory = OperatorSeededCsprng::from_initramfs(directory_seed_initramfs());
        let insufficient =
            OperatorSeededCsprng::from_seed_bytes(&PUBLIC_FIXTURE_SEED[..CSPRNG_SEED_BYTES - 1]);
        let oversized = OperatorSeededCsprng::from_seed_bytes(&OVERSIZED_PUBLIC_FIXTURE);

        assert_eq!(
            missing.readiness().state(),
            CsprngReadinessState::MissingSeed
        );
        assert_eq!(missing.readiness().state().name(), "csprng-missing-seed");
        assert_eq!(missing.readiness().seed_len(), None);
        assert_eq!(
            directory.readiness().state(),
            CsprngReadinessState::InvalidSeed
        );
        assert_eq!(
            insufficient.readiness(),
            CsprngReadinessReport::insufficient_seed(CSPRNG_SEED_BYTES - 1)
        );
        assert_eq!(
            oversized.readiness(),
            CsprngReadinessReport::invalid_seed(Some(OPERATOR_SEED_MAX_DIAGNOSTIC_BYTES + 1))
        );
    }

    #[test_case]
    fn not_ready_fill_zeroizes_caller_buffer_without_partial_output() {
        let mut csprng = OperatorSeededCsprng::from_seed_bytes(&PUBLIC_FIXTURE_SEED[..4]);
        let mut output = [0x5au8; 16];

        assert_eq!(
            csprng.fill_bytes(&mut output),
            Err(CsprngError::NotReady(
                CsprngReadinessState::InsufficientSeed
            ))
        );
        assert_eq!(output, [0u8; 16]);
    }

    #[test_case]
    fn public_fixture_seed_initializes_bounded_deterministic_output() {
        let mut first = OperatorSeededCsprng::from_seed_bytes(&PUBLIC_FIXTURE_SEED);
        let mut second = OperatorSeededCsprng::from_seed_bytes(&PUBLIC_FIXTURE_SEED);
        let mut first_output = [0u8; 32];
        let mut second_output = [0u8; 32];

        assert_eq!(first.readiness().state(), CsprngReadinessState::Ready);
        assert_eq!(
            first.readiness().seed_len(),
            Some(PUBLIC_FIXTURE_SEED.len())
        );
        assert!(first.readiness().cryptographic_strength());

        first.fill_bytes(&mut first_output).unwrap();
        second.fill_bytes(&mut second_output).unwrap();

        assert_eq!(first_output, second_output);
        assert_ne!(first_output, [0u8; 32]);
        first_output.zeroize();
        second_output.zeroize();
    }

    #[test_case]
    fn conditioner_accounts_for_seed_material_beyond_first_seed_block() {
        let mut base = [0x41u8; 64];
        let mut changed = base;
        changed[63] ^= 0x7f;

        let mut first = OperatorSeededCsprng::from_seed_bytes(&base);
        let mut second = OperatorSeededCsprng::from_seed_bytes(&changed);
        let mut first_output = [0u8; 16];
        let mut second_output = [0u8; 16];

        first.fill_bytes(&mut first_output).unwrap();
        second.fill_bytes(&mut second_output).unwrap();

        assert_ne!(first_output, second_output);
        first_output.zeroize();
        second_output.zeroize();
        base.zeroize();
        changed.zeroize();
    }

    const ROOT_INDEX: usize = 0;
    const ETC_INDEX: usize = 1;
    const TALOS_INDEX: usize = 2;
    const SEED_INDEX: usize = 3;

    static ROOT_ENTRIES: [DirectoryEntry; 1] = [DirectoryEntry::new(b"etc", ETC_INDEX)];
    static ETC_ENTRIES: [DirectoryEntry; 1] = [DirectoryEntry::new(b"talos", TALOS_INDEX)];
    static TALOS_ENTRIES: [DirectoryEntry; 1] =
        [DirectoryEntry::new(b"operator-seed.bin", SEED_INDEX)];
    static EMPTY_ENTRIES: [DirectoryEntry; 0] = [];
    static PUBLIC_FIXTURE_SEED: [u8; 48] = [
        0x70, 0x68, 0x61, 0x73, 0x65, 0x31, 0x32, 0x2d, 0x63, 0x73, 0x70, 0x72, 0x6e, 0x67, 0x2d,
        0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2d, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2d,
        0x76, 0x31, 0x2d, 0x6e, 0x6f, 0x74, 0x2d, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x21, 0x21,
        0x21, 0x21, 0x21,
    ];
    static OVERSIZED_PUBLIC_FIXTURE: [u8; OPERATOR_SEED_MAX_DIAGNOSTIC_BYTES + 1] =
        [0x42; OPERATOR_SEED_MAX_DIAGNOSTIC_BYTES + 1];

    static MISSING_SEED_NODES: [InitramfsNode; 3] = [
        InitramfsNode::directory(ROOT_INDEX, &ROOT_ENTRIES),
        InitramfsNode::directory(ETC_INDEX, &ETC_ENTRIES),
        InitramfsNode::directory(TALOS_INDEX, &EMPTY_ENTRIES),
    ];
    static DIRECTORY_SEED_NODES: [InitramfsNode; 4] = [
        InitramfsNode::directory(ROOT_INDEX, &ROOT_ENTRIES),
        InitramfsNode::directory(ETC_INDEX, &ETC_ENTRIES),
        InitramfsNode::directory(TALOS_INDEX, &TALOS_ENTRIES),
        InitramfsNode::directory(SEED_INDEX, &EMPTY_ENTRIES),
    ];

    const fn missing_seed_initramfs() -> ReadOnlyInitramfs {
        ReadOnlyInitramfs::new(&MISSING_SEED_NODES, ROOT_INDEX)
    }

    const fn directory_seed_initramfs() -> ReadOnlyInitramfs {
        ReadOnlyInitramfs::new(&DIRECTORY_SEED_NODES, ROOT_INDEX)
    }
}
